name: jhack
base: core20

architectures:
#  - build-on: s390x
#  - build-on: ppc64el
  - build-on: arm64
#  - build-on: armhf
  - build-on: amd64
  - build-on: i386

version: '0.2.91-dev'
summary: Cli tool packed with juju hacks.

description: |
  An opinionated collection of scripts and utilities to make 
  charming charming again.

grade: stable
confinement: strict

parts:
  jhack:
    plugin: python
    source: https://github.com/PietroPasotti/jhack.git
    source-branch: strict-snap
    python-packages:
      - typer==0.4.1
      - ops==1.4.0
      - rich==12.0.1
      - parse==1.19.0
      - juju==2.9.7
    stage-snaps:
      - juju/3.0/beta

apps:
  jhack:
    command: bin/jhack
    plugs:
      - juju-client-observe
      - dot-kubernetes
      - dot-local-share-juju
      - config-lxd
      - network
      - network-bind

plugs:
  peers:
    interface: content
    content: microk8s
    target: $SNAP_DATA/microk8s
  dot-kubernetes:
    interface: personal-files
    read:
      - $HOME/.kube
  dot-local-share-juju:
    interface: personal-files
    write:
      - $HOME/.local/share/juju
  config-lxd:
    interface: personal-files
    read:
      - $HOME/snap/lxd/common/config
